name: CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      # Установка зависимостей для сборки BLST
      - name: Install build dependencies
        run: sudo apt-get update && sudo apt-get install -y build-essential git

      # Сборка и установка BLST
      - name: Build and install BLST
        run: |
          git clone --depth 1 https://github.com/supranational/blst.git
          cd blst
          ./build.sh -shared        # or: make -C build
          sudo install -m755 libblst.so /usr/lib/
          sudo install -m644 bindings/blst.h /usr/include/
          sudo ldconfig
          cd ..

      - name: Set up PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: '8.2'
          extensions: ffi, gmp

      - name: Install dependencies
        run: composer install --prefer-dist --no-progress --no-suggest

      - name: Run PHPUnit tests
        run: vendor/bin/phpunit

      - name: Run Psalm
        run: vendor/bin/psalm

      - name: Run PHPStan
        run: vendor/bin/phpstan analyse src --level=max

      - name: Run PHP_CodeSniffer (PSR-12)
        run: vendor/bin/phpcs --standard=PSR12 --warning-severity=0 src/ tests/

      - name: Run Infection (mutation testing)
        run: vendor/bin/infection --threads=2